# TIMESTAMP: 2024-06-14 15:24:56.488
name: Push
on:
  push:
    branches:
      - main
jobs:
  security:
    name: Snyk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 #< https://github.com/actions/checkout
        with:
          fetch-depth: 0
      - name: List files in the repository
        run: |
          echo ${{ github.workspace }}
          ls -al ${{ github.workspace }}
      - name: Snyk Code scan
        # if: hashFiles('.snyk')
        uses: snyk/actions/php@master #< cf. https://github.com/snyk/actions/tree/master/php
        continue-on-error: true #< To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=low --show-vulnerable-paths=all --sarif-file-output=snyk.sarif
          json: true
        timeout-minutes: 360 #< maximum acc. to https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits
      - name: Upload result to GitHub Code Scanning
        if: hashFiles('snyk.sarif')
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif